all:alanu alau amanu amau
alanu:alloc_little_and_no_use.c
	gcc -o alanu alloc_little_and_no_use.c
alau:alloc_little_and_use.c
	gcc -o alau alloc_little_and_use.c
amanu:alloc_more_and_no_use.c
	gcc -o amanu alloc_more_and_no_use.c
amau:alloc_more_and_use.c
	gcc -o amau alloc_more_and_use.c
clean:
	rm -rf alanu
	rm -rf alau
	rm -rf amanu
	rm -rf amau

